import type { Language } from "./contentTypes";
import clientTranslations from "./clientGuides.translations.json";
import translations from "./productIntroduction.translations.json";

export type NavigationSection = {
  id: string;
  title: Record<Language, string>;
  children?: NavigationSection[];
};

type TranslationLanguage = Exclude<Language, "zh-CN">;
type TranslationMap = Partial<Record<TranslationLanguage, Record<string, string>>>;

const translatedText = translations as TranslationMap;
const clientTranslatedText = clientTranslations as TranslationMap;

const translated = (language: TranslationLanguage, id: string, label: string) =>
  translatedText[language]?.[`title.${id}`] ??
  clientTranslatedText[language]?.[`title.${id}`] ??
  label;

const title = (id: string, label: string): Record<Language, string> => ({
  en: translated("en", id, label),
  "zh-CN": label,
  "zh-TW": translated("zh-TW", id, label),
  de: translated("de", id, label),
  nl: translated("nl", id, label),
});

const section = (
  id: string,
  label: string,
  children?: NavigationSection[],
): NavigationSection => ({
  id,
  title: title(id, label),
  ...(children ? { children } : {}),
});

export const sections: NavigationSection[] = [
  section("products-services", "01 产品与服务", [
    section("product-introduction", "1.1 产品介绍", [
      section("product-name", "1.1.1 产品名称"),
      section("product-overview", "1.1.2 产品概述"),
      section("product-positioning", "1.1.3 产品定位"),
      section("product-service-regions", "1.1.4 服务区域"),
      section("product-clients-platforms", "1.1.5 客户端与平台"),
      section("product-network-capabilities", "1.1.6 核心网络能力"),
      section("product-protocols-technology", "1.1.7 协议与核心技术"),
      section("product-custom-nodes-protocols", "1.1.8 自定义节点与协议"),
      section("product-advanced-services", "1.1.9 高级服务"),
      section("product-node-services", "1.1.10 节点服务"),
      section("product-ai-support", "1.1.11 AI 辅助服务"),
      section("product-customer-service", "1.1.12 客户服务"),
      section("product-privacy-logs", "1.1.13 隐私与日志"),
      section("product-advertising-experience", "1.1.14 广告与产品体验"),
      section("product-open-source", "1.1.15 开源"),
      section("product-internal-technology", "1.1.16 未公开的内部技术"),
      section("product-design-principles", "1.1.17 产品设计原则"),
      section("product-service-boundaries", "1.1.18 产品服务边界"),
      section("product-information-priority", "1.1.19 产品信息的优先级"),
    ]),
    section("service-scope", "1.2 服务范围", [
      section("scope-overview", "1.2.1 服务范围概述"),
      section("official-service-countries", "1.2.2 正式服务国家"),
      section("service-countries-user-location", "1.2.3 服务国家与用户所在地"),
      section("non-official-service-users", "1.2.4 非正式服务国家或地区的用户"),
      section("cross-border-use", "1.2.5 用户跨境使用"),
      section("violations-service-restrictions", "1.2.6 违规使用及服务限制"),
      section("legal-regulatory-service-discontinuation", "1.2.7 因法律或监管原因无法继续提供服务"),
      section("service-countries-node-countries", "1.2.8 服务国家与官方节点国家"),
      section("official-node-status", "1.2.9 官方节点当前状态"),
      section("standard-nodes", "1.2.10 普通节点"),
      section("clean-nodes", "1.2.11 纯净节点"),
      section("node-ip-network-resources", "1.2.12 节点 IP 与网络资源"),
      section("node-sharing-user-counts", "1.2.13 节点共享与用户数量"),
      section("node-information-lookup", "1.2.14 节点信息查询"),
      section("pricing-country-differences", "1.2.15 服务价格与国家差异"),
      section("payment-methods-by-country", "1.2.16 支付方式"),
      section("free-service", "1.2.17 免费服务"),
      section("custom-nodes", "1.2.18 用户自定义节点"),
      section("country-law-service-availability", "1.2.19 国家法律与服务可用性"),
      section("united-states-service-scope", "1.2.20 美国服务范围"),
      section("schengen-service-scope", "1.2.21 申根区服务范围"),
      section("fixed-service-scope-policy", "1.2.22 服务范围固定政策"),
      section("scope-legal-compliance", "1.2.23 服务范围与法律合规的关系"),
      section("country-scope-reference-rules", "1.2.24 国家服务范围的引用规则"),
      section("scope-change-log", "1.2.25 服务范围变更记录"),
      section("scope-definitions", "1.2.26 本章节定义"),
    ]),
    section("service-model", "1.3 服务模式", [
      section("service-model-overview", "1.3.1 服务模式概述"),
      section("four-tier-service", "1.3.2 服务等级与权益"),
      section("traffic-service", "1.3.3 流量、订阅与定价"),
      section("custom-node-service", "1.3.4 自定义节点与账户资源"),
      section("service-model-principles", "1.3.5 服务原则与企业定制"),
    ]),
    section("supported-platforms", "1.4 支持的平台", [
      section("platform-overview", "1.4.1 支持平台"),
      section("windows-platform", "1.4.2 Windows"),
      section("android-platform", "1.4.3 Android"),
      section("linux-platform", "1.4.4 Linux"),
      section("cli-platform", "1.4.5 CLI"),
      section("apple-platforms", "1.4.6 Apple 平台"),
      section("cross-platform-account", "1.4.7 跨平台账户"),
      section("unsupported-platforms", "1.4.8 不支持的平台"),
      section("client-versions", "1.4.9 客户端版本"),
    ]),
    section("service-availability", "1.5 服务可用性", [
      section("availability-overview", "1.5.1 服务可用性概述"),
      section("node-availability", "1.5.2 节点、网络与维护"),
      section("service-failure", "1.5.3 故障、安全与不可控事件"),
      section("availability-boundaries", "1.5.4 可用性边界与状态信息"),
    ]),
    section("service-limitations", "1.6 服务限制与使用条件", [
      section("basic-use-conditions", "1.6.1 基本使用条件"),
      section("lawful-use", "1.6.2 合法使用"),
      section("official-node-limits", "1.6.3 官方节点使用限制"),
      section("node-credentials", "1.6.4 凭据、日志与安全限制"),
      section("service-abuse", "1.6.5 服务滥用与处理"),
      section("rule-priority", "1.6.6 规则适用与服务边界"),
    ]),
    section("user-responsibilities", "1.7 用户责任与义务", [
      section("user-basic-responsibility", "1.7.1 用户基本责任"),
      section("lawful-use-obligation", "1.7.2 合法使用义务"),
      section("account-security-responsibility", "1.7.3 账户、节点与凭据安全"),
      section("reasonable-resource-use", "1.7.4 设备、软件与资源使用"),
      section("network-security-responsibility", "1.7.5 网络安全、第三方与违规后果"),
      section("user-confirmation", "1.7.6 用户确认"),
    ]),
  ]),
  section("clients", "02 客户端", [
    section("windows-client", "2.1 Windows"),
    section("android-client", "2.2 Android"),
    section("linux-client", "2.3 Linux"),
    section("cli", "2.4 CLI", [
      section("cli-install", "2.4.1 安装"),
      section("cli-commands", "2.4.2 命令"),
      section("cli-configuration", "2.4.3 配置"),
      section("cli-linux", "2.4.4 Linux"),
      section("cli-raspberry-pi", "2.4.5 树莓派"),
      section("cli-arm-devices", "2.4.6 ARM 设备"),
      section("cli-servers", "2.4.7 服务器"),
      section("cli-compatible-devices", "2.4.8 其他兼容设备"),
    ]),
    section("iphone-client", "2.5 iPhone"),
    section("ipad-client", "2.6 iPad"),
    section("macos-client", "2.7 macOS"),
    section("cross-platform-features", "2.8 跨平台功能差异"),
  ]),
  section("account", "03 账户", [
    section("account-registration", "3.1 注册"),
    section("account-sign-in", "3.2 登录"),
    section("account-security", "3.3 账户安全"),
    section("password-authentication", "3.4 密码与身份验证"),
    section("device-management", "3.5 设备管理"),
    section("account-restrictions", "3.6 账户限制"),
    section("account-closure", "3.7 账户注销"),
    section("account-data-deletion", "3.8 数据删除"),
  ]),
  section("subscriptions-orders-payments", "04 订阅、订单与支付", [
    section("plans", "4.1 套餐"),
    section("pricing", "4.2 价格"),
    section("subscription-cycles", "4.3 订阅周期"),
    section("payment-methods", "4.4 支付方式"),
    section("orders", "4.5 订单"),
    section("invoices-payment-proof", "4.6 发票与付款凭证"),
    section("auto-renewal", "4.7 自动续费"),
    section("cancel-subscription", "4.8 取消订阅"),
    section("refunds", "4.9 退款"),
    section("taxes", "4.10 税费"),
    section("payment-failures", "4.11 支付失败"),
    section("regional-payment-differences", "4.12 国家与地区差异"),
    section("card-wallet-benefits", "4.13 卡包与权益规则"),
  ]),
  section("service-regions-nodes", "05 服务区域与节点", [
    section("service-region-overview", "5.1 服务区域总览"),
    section("united-states", "5.2 美国", [
      section("us-general-rules", "5.2.1 美国通用规则"),
      section("us-node-regions", "5.2.2 节点区域"),
      section("us-state-differences", "5.2.3 州级差异"),
      section("us-special-regions", "5.2.4 特殊地区"),
    ]),
    section("schengen-area", "5.3 申根区", [
      section("schengen-general-rules", "5.3.1 申根区通用规则"),
      section("schengen-countries", "5.3.2 29 国列表"),
      section("schengen-country-differences", "5.3.3 国家差异"),
      section("schengen-special-countries", "5.3.4 特殊国家"),
    ]),
    section("country-service-matrix", "5.4 国家服务矩阵"),
    section("node-selection", "5.5 节点选择"),
    section("node-status", "5.6 节点状态"),
    section("node-maintenance", "5.7 节点维护"),
    section("node-failover", "5.8 节点故障与切换"),
  ]),
  section("network-connection", "06 网络与连接", [
    section("vpn-operation", "6.1 VPN 工作方式"),
    section("connection", "6.2 连接"),
    section("automatic-connection", "6.3 自动连接"),
    section("automatic-reconnection", "6.4 自动重连"),
    section("network-switching", "6.5 网络切换"),
    section("routing", "6.6 路由"),
    section("split-tunneling", "6.7 分流"),
    section("dns", "6.8 DNS"),
    section("ipv4", "6.9 IPv4"),
    section("ipv6", "6.10 IPv6"),
    section("local-network", "6.11 局域网"),
    section("dns-leak-protection", "6.12 DNS 泄漏防护"),
    section("ipv6-leak-protection", "6.13 IPv6 泄漏防护"),
    section("speed-latency", "6.14 速度与延迟"),
  ]),
  section("security-privacy", "07 安全与隐私", [
    section("security-overview", "7.1 安全概览"),
    section("privacy-overview", "7.2 隐私概览"),
    section("data-collected", "7.3 收集的数据"),
    section("data-purpose", "7.4 数据使用目的"),
    section("data-processing", "7.5 数据处理"),
    section("data-retention", "7.6 数据保存期限"),
    section("data-deletion", "7.7 数据删除"),
    section("data-access", "7.8 数据访问"),
    section("data-correction", "7.9 数据更正"),
    section("data-portability", "7.10 数据可携带"),
    section("restriction-of-processing", "7.11 限制处理"),
    section("objection-to-processing", "7.12 反对处理"),
    section("data-security", "7.13 数据安全"),
    section("data-breaches", "7.14 数据泄露"),
    section("privacy-third-party-services", "7.15 第三方服务"),
    section("cross-border-data-transfers", "7.16 跨境数据传输"),
    section("cookie-policy", "7.17 Cookie"),
    section("online-tracking", "7.18 在线追踪"),
  ]),
  section("service-rules", "08 服务规则", [
    section("terms-of-service", "8.1 服务条款"),
    section("acceptable-use-policy", "8.2 可接受使用政策"),
    section("prohibited-activities", "8.3 禁止行为"),
    section("account-abuse", "8.4 账户滥用"),
    section("service-rule-limitations", "8.5 服务限制"),
    section("service-suspension", "8.6 服务暂停"),
    section("service-termination", "8.7 服务终止"),
    section("service-rule-user-responsibilities", "8.8 用户责任"),
    section("service-responsibilities", "8.9 服务责任"),
    section("intellectual-property", "8.10 知识产权"),
    section("terms-changes", "8.11 条款修改"),
  ]),
  section("legal-regulation", "09 法律与监管", [
    section("applicable-law", "9.1 适用法律范围"),
    section("europe", "9.2 欧洲地区", [
      section("gdpr", "9.2.1 GDPR"),
      section("data-subject-rights", "9.2.2 数据主体权利"),
      section("legal-basis-processing", "9.2.3 数据处理法律依据"),
      section("europe-data-security", "9.2.4 数据安全"),
      section("europe-data-breaches", "9.2.5 数据泄露"),
      section("europe-cross-border-transfers", "9.2.6 数据跨境传输"),
      section("data-protection-impact-assessment", "9.2.7 数据保护影响评估"),
      section("data-protection-officer", "9.2.8 数据保护负责人"),
      section("europe-country-differences", "9.2.9 国家级差异"),
    ]),
    section("united-states-law", "9.3 美国", [
      section("us-federal-law", "9.3.1 联邦法律"),
      section("us-state-privacy-laws", "9.3.2 州级隐私法律"),
      section("consumer-rights", "9.3.3 消费者权益"),
      section("us-data-security", "9.3.4 数据安全"),
      section("us-data-breaches", "9.3.5 数据泄露"),
      section("us-law-state-differences", "9.3.6 州级差异"),
      section("special-industry-rules", "9.3.7 特殊行业规则"),
    ]),
    section("consumer-protection", "9.4 消费者保护"),
    section("digital-services", "9.5 数字服务"),
    section("online-sales", "9.6 在线销售"),
    section("online-payments", "9.7 在线支付"),
    section("advertising-marketing", "9.8 广告与营销"),
    section("minors", "9.9 未成年人"),
    section("legal-intellectual-property", "9.10 知识产权"),
    section("law-enforcement-requests", "9.11 执法请求"),
    section("legal-user-requests", "9.12 用户法律请求"),
    section("legal-changes", "9.13 法律变更"),
  ]),
  section("formal-legal-documents", "10 正式法律文件", [
    section("formal-terms", "10.1 服务条款"),
    section("formal-privacy-policy", "10.2 隐私政策"),
    section("formal-cookie-policy", "10.3 Cookie 政策"),
    section("formal-acceptable-use-policy", "10.4 可接受使用政策"),
    section("refund-policy", "10.5 退款政策"),
    section("data-processing-documents", "10.6 数据处理相关文件"),
    section("data-subject-request-guidance", "10.7 数据主体请求说明"),
    section("security-breach-notices", "10.8 安全与数据泄露通知"),
    section("open-source-licenses", "10.9 开源许可证"),
    section("legal-contact-information", "10.10 法律联系信息"),
  ]),
  section("open-source-technology", "11 开源与技术", [
    section("open-source-projects", "11.1 开源项目"),
    section("technology-licenses", "11.2 开源许可证"),
    section("technical-architecture", "11.3 技术架构"),
    section("vpn-protocols", "11.4 VPN 协议"),
    section("encryption-technology", "11.5 加密技术"),
    section("tunneling-technology", "11.6 隧道技术"),
    section("routing-system", "11.7 路由系统"),
    section("dns-system", "11.8 DNS 系统"),
    section("configuration-formats", "11.9 配置格式"),
    section("protocol-version-history", "11.10 协议版本"),
    section("security-vulnerability-disclosure", "11.11 安全漏洞披露"),
  ]),
  section("api", "12 API", [
    section("api-overview", "12.1 API 概览"),
    section("api-endpoints", "12.2 API 地址"),
    section("api-version", "12.3 API 版本"),
    section("api-authentication", "12.4 身份认证"),
    section("api-keys", "12.5 API 密钥"),
    section("user-api", "12.6 用户接口"),
    section("account-api", "12.7 账户接口"),
    section("subscription-api", "12.8 订阅接口"),
    section("order-api", "12.9 订单接口"),
    section("node-api", "12.10 节点接口"),
    section("device-api", "12.11 设备接口"),
    section("network-api", "12.12 网络接口"),
    section("webhooks", "12.13 Webhook"),
    section("api-error-codes", "12.14 错误码"),
    section("api-rate-limits", "12.15 请求限制"),
    section("api-compatibility", "12.16 API 兼容性"),
  ]),
  section("troubleshooting", "13 故障排查", [
    section("login-problems", "13.1 登录问题"),
    section("connection-problems", "13.2 连接问题"),
    section("internet-access-problems", "13.3 无法访问互联网"),
    section("dns-problems", "13.4 DNS 问题"),
    section("ipv6-problems", "13.5 IPv6 问题"),
    section("speed-problems", "13.6 速度问题"),
    section("latency-problems", "13.7 延迟问题"),
    section("frequent-disconnections", "13.8 频繁断线"),
    section("network-switching-problems", "13.9 网络切换问题"),
    section("payment-problems", "13.10 支付问题"),
    section("account-problems", "13.11 账户问题"),
    section("troubleshooting-logs-diagnostics", "13.12 日志与诊断"),
  ]),
  section("appendix", "14 附录", [
    section("glossary", "14.1 常用术语"),
    section("country-region-codes", "14.2 国家与地区代码"),
    section("platform-compatibility-matrix", "14.3 平台兼容性矩阵"),
    section("feature-support-matrix", "14.4 功能支持矩阵"),
    section("appendix-country-service-matrix", "14.5 国家服务矩阵"),
    section("protocol-version-history-appendix", "14.6 协议版本历史"),
    section("api-version-history", "14.7 API 版本历史"),
    section("service-change-log", "14.8 服务变更记录"),
    section("security-bulletins", "14.9 安全公告"),
    section("documentation-change-log", "14.10 文档变更记录"),
    section("format-demonstration", "14.11 标准"),
  ]),
];
